# Generated by Django 3.0.3 on 2020-08-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('Required_for', models.CharField(choices=[('NGO', 'NGO'), ('SELF', 'SELF')], default='NGO', max_length=100)),
                ('Organisation_name', models.CharField(max_length=123)),
                ('Phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
