# Generated by Django 3.0.3 on 2020-08-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('required', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='Organisation_name',
            new_name='Ngo_name',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='Required_for',
            new_name='Required_For',
        ),
    ]
