# Generated by Django 3.0.3 on 2020-08-29 10:32

from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=246)),
                ('email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=246)),
                ('city', models.CharField(default='Dehradun', max_length=246)),
                ('Phone', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=246)),
                ('author', models.CharField(max_length=246)),
                ('standard', models.CharField(choices=[('primary_school', 'PRIMARY SCHOOL'), ('secondary_school', 'SECONDARY SCHOOL')], default='PRIMARY SCHOOL', max_length=100)),
                ('condition', models.CharField(choices=[('good', 'GOOD'), ('average', 'AVERAGE'), ('bad', 'BAD')], default='GOOD', max_length=100)),
                ('book_photo', models.ImageField(blank=True, upload_to='book_photos')),
            ],
        ),
    ]
